DepartmentOfHealth-htbhf/htbhf-applicant-web-ui

src/test/acceptance/features/enter-name.feature, src/test/acceptance/features/overview.feature, src/test/common/steps/enter-name-steps.js, src/test/common/steps/overview-steps.js, src/web/routes/application/enter-name/enter-name.js, src/web/routes/application/enter-nino/enter-nino.js, src/web/routes/register-routes.js, src/web/views/start.njk
Switched enter nino and enter name page order. Enter nino is now before enter name.
=> HTBHF-8 Fixed ordering of pages.

src/web/routes/application/enter-name/enter-name.js, src/web/routes/application/enter-name/index.js, src/web/routes/application/enter-nino/enter-nino.js, src/web/routes/application/enter-nino/index.js, src/web/routes/application/register-form-routes.js, src/web/routes/application/steps.js, src/web/routes/register-routes.js
Adding new form routes to the application results in a lot of duplicate code. To remain DRY a factory style function has been implemented to register routes based on an array of configuration objects for each route.
=> HTBHF-288 Refactor form routes registration

package.json, src/test/acceptance/acceptance-report.js, src/test/common/driver/driver-manager.js, src/test/common/steps/hooks.js, src/test/common/steps/pages.js, src/test/common/steps/test-startup-config.js, src/test/compatibility/compatibility-report.js, src/test/compatibility/config/constants.js, src/test/compatibility/driver/browserstack-driver.js, src/test/compatibility/features/enter-name.feature, src/test/compatibility/features/smoke-test.feature, src/test/smoke/config/environment.js, src/test/smoke/smoke-report.js
We can now run compatibility tests using browserstack from web-ui. Currently this is only triggered manually, the separate compatibility tests project remains the active suite of tests for now.
=> Added compatibility tests

src/web/routes/application/are-you-pregnant/are-you-pregnant.js, src/web/server/locales/cy/common.json, src/web/server/locales/en/common.json, src/web/server/view-engine/view-engine.js, src/web/views/are-you-pregnant.njk, src/web/views/enter-dob.njk, src/web/views/macros/htbhf-date-input.njk
- Add conditional EDD field to UI
- Refactor date input field into common nunjucks macro
=> HTBHF-412 Add conditional EDD field to UI

package.json
Allow running of unit tests independently of coverage report
=> HTBHF-413 create distinct unit tests and coverage targets

package-lock.json, package.json, src/web/server/configure-security.js, src/web/server/server.js
- Add Helmet to secure express server
- Add content security policy
=> HTBHF-275 add security middleware

src/web/routes/application/middleware/handle-post.js, src/web/routes/application/middleware/handle-post.test.js, src/web/routes/application/register-form-routes.js
- Identify active step (from steps configuration array) by path
- Set step's `next` property as `nextAllowedStep` in session
=> HTBHF-605 save next available step in session

src/test/common/page/are-you-pregnant.js, src/test/common/page/check.js, src/test/common/page/page.js, src/test/common/steps/are-you-pregnant.js, src/test/common/steps/hooks.js, src/test/common/steps/navigation.js
- Fix issue with are you pregnant steps and pages not working correctly (not doing any assertions) and properly waiting for Promises to resolve before finishing the tests - this would result in a UnhandledPromise error being thrown to the console.
- Also added a number of extra try/catch blocks around areas of code that were investigated for this fix.
- Remove extraneous Promise.all call from getting the check details table contents.
=> Fix are you pregnant step Promises

src/test/acceptance/features/unsuccessful-application.feature, src/test/common/steps/unsuccessful-application.js, src/test/common/wiremock.js, src/web/server/locales/cy/common.json, src/web/server/locales/en/common.json
Updating `NOMATCH` -> `NO_MATCH` to follow updates to claimant service
=> HTBHF-1160 update no match casing to match response from service

src/test/common/wiremock.js
Updates wiremock responses to match updates to the claimant service. See https://github.com/DepartmentOfHealth-htbhf/htbhf-claimant-service/pull/172/files
=> HTBHF-1362 update wiremock to match claimant service response

src/test/acceptance/features/are-you-pregnant.feature, src/test/acceptance/features/enter-nino.feature, src/test/acceptance/features/internationalisation.feature, src/test/acceptance/features/navigation.feature, src/test/acceptance/features/overview.feature, src/test/common/page/are-you-pregnant.js, src/test/common/steps/check-details.js, src/test/common/steps/common-steps.js, src/test/common/steps/complete-flow.js, src/test/common/steps/internationalisation.js, src/test/common/steps/navigation.js, src/test/common/steps/overview-steps.js, src/test/common/steps/pages.js, src/test/smoke/features/smoke-test.feature, src/web/routes/application/are-you-pregnant/are-you-pregnant.js, src/web/routes/application/enter-nino/enter-nino.js, src/web/routes/application/steps.js
- Reorder sequence of questions in UI to match prototype
- Update browser tests to match reordered UI sequence
- Refactor internationalisation feature to avoid renaming of scenarios as new steps are added to the start of the application
- Create a single `startApplication()` function to avoid multiple updates as new pages are added to the start of the application
=> Reorder UI sequence

src/test/acceptance/features/are-you-pregnant.feature, src/test/acceptance/features/check-details.feature, src/test/acceptance/features/do-you-live-in-scotland.feature, src/test/acceptance/features/navigation.feature, src/test/common/page/are-you-pregnant.js, src/test/common/page/do-you-live-in-scotland.js, src/test/common/steps/are-you-pregnant.js, src/test/common/steps/common-steps.js, src/test/common/steps/do-you-live-in-scotland-steps.js, src/test/common/steps/navigation.js, src/web/routes/application/are-you-pregnant/validate.js, src/web/routes/application/common/validators.js, src/web/routes/application/do-you-live-in-scotland/do-you-live-in-scotland.js, src/web/routes/application/do-you-live-in-scotland/validate.js
- Add validation to "Do you live in Scotland?"
- Shared code from "Are you pregnant?" has been refactored into common functions
=> HTBHF-1557 add validation for do you live in Scotland

src/web/routes/application/children-dob/children-dob.js, src/web/routes/application/children-dob/children-dob.test.js, src/web/routes/application/register-form-routes.js, src/web/views/children-dob.njk, src/web/views/macros/htbhf-child-dob-input.njk
- Implement custom step behaviour for POST
- Add a single child's DOB to the session and make available to the view (on add) using custom step behaviour
- Initialise child count in session as a static number (1)
=> HTBHF-1677 make childrens DOBs available to the view

src/test/acceptance/features/do-you-have-children.feature, src/test/acceptance/features/enter-children-dob.feature, src/test/common/page/do-you-have-children-three-or-younger.js, src/test/common/steps/common-steps.js, src/test/common/steps/do-you-have-children-three-or-under-steps.js, src/web/server/locales/en/common.json, src/web/server/locales/en/validation.json
- Removed the word 'any' from the children's dates of birth question
- Updated hint text for do you have children question
=> HTBHF-1588 update content for children's dates of birth

src/web/routes/application/are-you-pregnant/are-you-pregnant.js, src/web/routes/application/are-you-pregnant/are-you-pregnant.test.js, src/web/routes/application/children-dob/children-dob.js, src/web/routes/application/common/formatters/dates.js, src/web/routes/application/common/formatters/dates.test.js, src/web/server/locales/en/common.json
- Move example date function into common formatters
- Update example date function to use moment JS
- Add example date to children's dates of birth hint text
=> Children's dates of birth page example date

src/test/acceptance/features/do-you-have-children.feature, src/test/acceptance/features/enter-children-dob.feature, src/test/common/page/enter-children-dob.js, src/test/common/page/page.js, src/test/common/steps/enter-children-dob-steps.js
Currently have the main remove child test @ignore until functionality is complete. Testing of the presence and absence of remove buttons has been added to existing add child tests.
=> HTBHF-1705 Add acceptance tests for the Remove Child button.

src/web/routes/application/enter-code/enter-code.js, src/web/routes/application/enter-nino/enter-nino.js, src/web/server/locales/cy/common.json, src/web/server/locales/en/common.json, src/web/views/enter-code.njk
All of the html for the request new code link has been put into a translation file as other languages may have different ordering of words and the two parts of the sentence translated separately may not make sense when concatenated.
=> HTBHF-1735 Updated translation link for enter code page.

src/test/acceptance/features/address.feature, src/test/acceptance/features/are-you-pregnant.feature, src/test/acceptance/features/check-details.feature, src/test/acceptance/features/confirm.feature, src/test/acceptance/features/confirmation-code-navigation.feature, src/test/acceptance/features/cookies.feature, src/test/acceptance/features/do-you-have-children.feature, src/test/acceptance/features/do-you-live-in-scotland.feature, src/test/acceptance/features/email-address.feature, src/test/acceptance/features/enter-children-dob.feature, src/test/acceptance/features/enter-code.feature, src/test/acceptance/features/enter-dob.feature, src/test/acceptance/features/enter-name.feature, src/test/acceptance/features/enter-nino.feature, src/test/acceptance/features/error-page.feature, src/test/acceptance/features/internationalisation.feature, src/test/acceptance/features/overview.feature, src/test/acceptance/features/page-not-found.feature, src/test/acceptance/features/phone-number.feature, src/test/acceptance/features/privacy-notice.feature, src/test/acceptance/features/send-code.feature, src/test/acceptance/features/terms-and-conditions.feature, src/test/acceptance/features/unsuccessful-application.feature, src/test/common/page/overview.js, src/test/compatibility/features/apply-success.feature, src/test/smoke/features/smoke-test.feature, src/web/views/templates/page.njk
Have also updated the programme name in the feature files too.
=> HTBHF-1795 Change service name to Apply for Healthy Start in banner plus feature files.

src/test/common/page/address.js, src/web/routes/application/address/address.js, src/web/server/locales/cy/common.json, src/web/server/locales/en/common.json, src/web/views/address.njk
- Updated address page to match prototype.
- Removed hidden labels on address line 1 and 2 as we now have a label per input.
=> HTBHF-1846 Update address content.

src/test/acceptance/features/change-children.feature, src/test/common/steps/check-details.js, src/web/routes/application/common/state-machine/state-machine.js, src/web/routes/application/common/state-machine/state-machine.test.js, src/web/routes/application/do-you-have-children-three-or-younger/do-you-have-children-three-or-younger.js, src/web/server/locales/en/common.json, src/web/views/check.njk, src/web/views/macros/htbhf-summary-list.njk
- Add “do you have any children?” to check details page
- Invalidate review if user changes answer for “do you have any children?” from “no” to “yes”
=> Check details for “Do you have any children?”

src/test/common/steps/check-details.js, src/web/routes/application/do-you-have-children-three-or-younger/do-you-have-children-three-or-younger.js
Add missing assertions on check details page acceptance tests for “Do you have children?”
=> Do you have children acceptance tests for check details page

src/test/common/page/page.js, src/test/common/steps/check-details.js, src/web/views/check.njk
If an applicant has answered “No” to “Do you have children?” then the children’s dates of birth summary list should not be displayed.
=> HTBHF-1852 assert children’s dates of birth summary list is not displayed

src/web/views/check.njk
Fix for style bug introduced in previous PR where spacing between summary lists is incorrect
=> HTBHF-1852 fix summary list styles

src/test/a11y/test-suite.js, src/test/common/page/do-you-have-children.js, src/test/common/steps/check-details.js, src/test/common/steps/common-steps.js, src/test/common/steps/confirmation-code-navigation-steps.js, src/test/common/steps/do-you-have-children-steps.js, src/test/common/steps/internationalisation.js, src/test/common/steps/navigation.js, src/test/common/steps/pages.js, src/web/routes/application/children-dob/children-dob.js, src/web/routes/application/do-you-have-children/do-you-have-children.js, src/web/routes/application/do-you-have-children/do-you-have-children.test.js, src/web/routes/application/do-you-have-children/index.js, src/web/routes/application/do-you-have-children/validate.js, src/web/routes/application/steps.js, src/web/server/locales/cy/common.json, src/web/server/locales/cy/validation.json, src/web/server/locales/en/common.json, src/web/server/locales/en/validation.json, src/web/views/do-you-have-children.njk
Step 3 of renaming “Do you have children three or under?”. The end result after all PRs will be:
Production code: “Do you have children?”
Feature files: “Do you have children under four years old?”
Path: /do-you-have-children
=> HTBHF-1670 rename references to do you have children

.travis.yml, package-lock.json, package.json, sample.env, src/test/common/config.js, src/test/common/driver/driver-manager.js
- Install latest version of Firefox in travis to run headless tests
- Add geckodriver dependency for Firefox testing
- Add environment variable to run either Chrome or Firefox headless for tests, defaults to Chrome
=> Resolve issue with Chrome headless browser for browser tests

src/web/assets/sass/all.scss, src/web/assets/sass/components/_pagination.scss, src/web/views/macros/htbhf-pagination.njk, src/web/views/partials/icons/arrow-next.njk, src/web/views/partials/icons/arrow-previous.njk, src/web/views/templates/guidance.njk
- Create SASS component for previous / next pagination on guidance pages
- Create Nunjucks macro for previous / next pagination on guidance pages
- Create partials directory and add SVG arrow icons
- Update spacing on section break to allow for pagination hover state
=> Guidance pages pagination

package-lock.json
Fixed with `npm audit fix` to update vulnerable packages
=> NO-JIRA fix NPM package vulnerabilities

src/test/a11y/test-suite.js, src/test/acceptance/features/manual-address.feature, src/test/common/page/manual-address.js, src/test/common/steps/common-steps.js, src/test/common/steps/constants.js, src/test/common/steps/manual-address-steps.js, src/web/routes/application/manual-address/test/validation-composition.test.js, src/web/routes/application/manual-address/validate.js
Added validation for acceptance tests for county address field.
=> HTBHF-1915 Added validation of county field.

.travis.yml, package-lock.json, package.json, sample.env, src/test/common/config.js, src/test/common/driver/driver-manager.js
The latest version of selenium seems to work with headless chrome, so the switch I've added here isn't strictly necessary. Seems nicer than having to edit code to change between modes though.
=> HTBHF-1972 Updated to latest version of selenium and enabled config switch for headless mode

src/web/views/locales/cy/privacy-notice.njk, src/web/views/locales/en/privacy-notice.njk
Updated missing content, added class to links.
=> HTBHF-898 Updated privacy notice content.

.gitignore
- Ignore Visual Studio Code local history
- Ignore Visual Studio Code debug config
=> NO-JIRA ignore visual studio code specific files and directories

manifest.yml, sample.env, src/config/environment.js, src/config/vcap-services.js
Connecting to address lookup variable service.
=> HTBHF-2044 Connecting to address lookup variable service.

src/web/views/locales/cy/privacy-notice.njk, src/web/views/locales/en/privacy-notice.njk
Content updated to match latest design doc https://docs.google.com/document/d/1W44YqlBqTZmwdwNL8tNSURe7Vc2_Cc2mGEz2Y5qqCvw/edit. 
At time of writing the prototype has not been updated so use the doc as reference for reviewing.
=> HTBHF-898 Content update for privacy notice.

features.json, src/config/features.js, src/web/routes/register-steps/register-steps.js
- Set features in top level JSON file to allow other services to easily consume features
- Import features JSON into environment config
=> HTBHF-2067 set features in top level JSON file

README.md, src/test/a11y/run-test-suite.js, src/test/a11y/test-suite.js, src/test/a11y/tests/configure-test-suite.js, src/test/a11y/tests/index.js, src/test/integration/run-test-suite.js
Filter steps in a11y tests to remove steps that are feature toggled off
=> HTBHF-2066 apply feature toggle to a11y tests

src/web/routes/application/check/get.js, src/web/routes/application/send-code/send-code.js, src/web/server/locales/cy/common.json, src/web/server/locales/en/common.json, src/web/views/postcode.njk
- Moved change link to common section of translation files as this is used by more than one page.
- Removed unused import in postcode template.
=> HTBHF-1891 Moved the change link to bottom level of translation files.

LICENSE, manifest.yml, src/config/vcap-services.test.js, src/test/session-details-provider/README.md, src/test/session-details-provider/session-details-manifest.yml
Rename references for **Help to Buy Healthy Food** -> **Apply for Healthy Start**
=> HTBHF-2138 rename to Apply for Healthy Start

src/test/acceptance/features/cookies.feature, src/test/acceptance/features/general-page.feature, src/test/acceptance/features/privacy-notice.feature, src/test/common/page/page.js, src/test/common/steps/common-steps.js, src/test/common/steps/cookie-steps.js, src/test/common/steps/privacy-notice-steps.js, src/web/views/templates/page.njk
- Update feedback link as per JIRA ticket.
- Created general-page.feature to encapsulate the AT for this ticket and moved back link ATs for privacy-page and cookies page to it.
- Spotted and removed duplication in back link step methods.
=> HTBHF-2155 Update the beta banner to have a feedback link.

src/web/routes/application/terms-and-conditions/post.js, src/web/routes/application/terms-and-conditions/post.test.js
Also renamed `transofrmResponse` to `handleErrorResponse`
=> HTBHF-2189 Added error response from claimant service to Error when thrown

src/web/routes/application/select-address/select-address.js, src/web/routes/application/select-address/select-address.test.js, src/web/views/select-address.njk
The claim on the session is now updated with the address selected from the select-address page. The address format is the same as that of manual-address.
=> HTBHF-2167 Updated claim with address from select address page.

src/test/acceptance/features/address-lookup.feature, src/test/common/steps/address-lookup-steps.js
Happy 😊 and sad 😞 path user journey acceptance tests for postcode lookup on select address page.
=> HTBHF-2174 add select address acceptance tests

src/web/routes/application/address/postcode/adapters.js, src/web/routes/application/address/postcode/adapters.test.js, src/web/routes/application/address/postcode/postcode.test.js, src/web/routes/application/address/postcode/test-fixtures.json
Also removed postcode from the address summary.
=> HTBHF-2203 Converted addresses from OS Places to title case

src/web/routes/application/common/state-machine/state-machine.js, src/web/routes/application/common/state-machine/state-machine.test.js
Only logging and setting the state in setState if the state has changed.
=> HTBHF-2037 Set state no longer logs if the state isn't changing.

src/web/routes/application/check-answers/get-row-data.js, src/web/routes/application/check-answers/get-row-data.test.js, src/web/routes/application/check-answers/get.js
This is a branch I created when working with @mikeSmith08 on children DOBs for the check answers page. I revisited these files with @YetAnotherMatt recently and found `get-row-data.js` difficult to understand .. so I'm putting this up for a PR as I think it makes the data transformations for the check answers page a bit more obvious.
.. feel free to decline if you don't feel this is necessary or any better than the original file.
=> NO-JIRA refactor data transformations for check answers

src/web/routes/application/address/postcode/postcode.test.js
Fix the test `behaviourForPost() does not call os places when there are validation errors` which was passing incorrectly.
=> HTBHF-2177 fix postcode unit test

src/test/common/driver/driver-manager.js
Setting chrome options to avoid intermittent errors starting chrome
=> NOJIRA Added no-sandbox and disable-dev-shm-usage to chrome options.

test_versions.properties
This will pick up the dynamic capability file list for BrowserStack tests.
=> Update to latest acceptance test version.

src/test/a11y/paths.js, src/test/a11y/tests/apply.js, src/test/session-details-provider/constants.js, src/test/session-details-provider/index.js, src/test/session-details-provider/session-details-app.js
- Move session details config to session details directory
- Remove redundant export of PORT
- Delete config.js
=> NO-JIRA refactor test config

src/web/routes/application/flow-control/state-machine/keys.js, src/web/routes/application/flow-control/state-machine/operators.js, src/web/routes/application/flow-control/state-machine/session-accessors.js, src/web/routes/application/flow-control/state-machine/session-accessors.test.js, src/web/routes/application/flow-control/state-machine/state-machine.js
Create utility functions for getting / setting properties on state for each journey. Will be implemented in the state machine in a future PR.
=> HTBHF-2548 create state machine journey based operators

src/web/server/locales/en/common.json
Updated first and last name labels to match the prototype https://htbhf-prototype.herokuapp.com/BASELINE/what-is-your-name
=> HTBHF-2436 Updated first and last name labels.

README.md
All documentation for the project has been updated and migrated to the wiki. The README has been updated to link to pages in the wiki.
=> HTBHF-2634 update README to reference project wiki

src/test/a11y/paths.js, src/test/a11y/tests/apply.js, src/web/routes/application/flow-control/middleware/handle-path-request/handle-path-request.js, src/web/routes/application/flow-control/middleware/handle-path-request/handle-path-request.test.js, src/web/routes/application/flow-control/state-machine/state-machine.js, src/web/routes/application/flow-control/state-machine/state-machine.test.js, src/web/routes/application/paths/paths.js, src/web/routes/application/register-journeys.js, src/web/routes/application/register-journeys.test.js, src/web/routes/application/steps/confirm/confirm.js, src/web/routes/application/steps/terms-and-conditions/post.js, src/web/routes/application/steps/terms-and-conditions/post.test.js, test_versions.properties
Update URL for last page of application from `/confirm` to `/decision`. The next PR will rename `confirm` functions, directories and files.
=> HTBHF-2490 update confirm URL and constants

src/web/routes/application/flow-control/keys.js, src/web/routes/application/flow-control/middleware/render-view/render-view.js, src/web/routes/application/flow-control/middleware/render-view/render-view.test.js, src/web/routes/application/flow-control/middleware/session-details.js, src/web/routes/application/flow-control/middleware/session-details.test.js, src/web/routes/application/flow-control/session-accessors/index.js, src/web/routes/application/flow-control/session-accessors/session-accessors.js, src/web/routes/application/flow-control/session-accessors/session-accessors.test.js
render-view.js now adds any additionalData for the current step to res.locals
=> HTBHF-2675 Added methods for storing and retrieving additional step-related data from the session

src/web/routes/application/flow-control/index.js, src/web/routes/application/steps/address/select-address/select-address.js, src/web/routes/application/steps/address/select-address/select-address.test.js, src/web/routes/application/steps/address/select-address/validate.js, src/web/server/locales/cy/validation.json, src/web/server/locales/en/validation.json, src/web/views/select-address-form.njk
Also validating that an address has been selected
=> HTBHF-2675 Changed select-address to store address data in session.stepData instead of res.locals

src/test/a11y/wiremock/claim/mappings/mappings.js, src/test/a11y/wiremock/claim/mappings/v3.js, src/web/routes/application/journey-definitions.js, test_versions.properties
- Create wiremock mapping for V3 claimant service endpoint
- Update "apply" journey definition to point at V3 endpoint
=> HTBHF-1942 point apply journey to use claimant service V3 endpoint

test_versions.properties
changed the test-version to latest release to run the acceptance tests
=> added latest test version to run the acceptance tests
