- src/web/routes/application/check/get.js
Using ramda pick requires a null check on `req.session.claim`. As this data is not sent to the client it seems better to pass the whole `claim` object to the view. No null check is required for this as session will always be defined.
> HTBHF-8 Fix check details error if no claim present on session

- src/web/views/check.njk
I've added both are you pregnant and expected delivery date - which will always appear. I expect HTBHF-18 (check your answers) to fix the display of the due date.
> HTBHF-418 Added expected delivery date to the check details page

- .travis.yml
Travis no longer supports version 10.10 of node so we're updating the version to use to 10.15.0
> NO-JIRA Changing node version on travis to 10.15

- src/web/routes/application/common/state-machine/state-machine.js
- src/web/routes/application/common/state-machine/state-machine.test.js
- src/web/routes/application/middleware/handle-path-request.js
- src/web/routes/application/middleware/handle-post-redirects.js
- src/web/routes/application/middleware/handle-post.js
Apply req as first argument to state machine functions.
This allows us to remove arguments that are properties of the `req` object as a reference to `req` is always passed to a state machine action. This reduces the number of parameters passed to dispatch.
> HTBHF-485 apply req as first argument to state machine functions

- package.json
- src/web/logger/logger.js
Wiremock 500 responses are causing the app to log errors during acceptance tests that pollute the console output. Adding `LOG_LEVEL=silent` as an environment variable when running acceptance tests will now silence the logger.
A noisy console has caused us to ignore actual errors in our acceptance tests. Keeping the console noise free should force us to fix any future errors that appear.
Are there any situations where turning off logging during acceptance tests could be an issue?
> NO-JIRA add silent configuration to logger

- src/web/routes/application/check/post.js
- src/web/routes/application/check/post.test.js
Note, additional acceptance tests and content will be created in a future PR. This PR is up so that the service doesn't break when the api changes for the claimant service goes in.
> HTBHF-640 Handle 404 responses from claimant service.

- src/web/routes/application/check/post.js
- src/web/routes/application/check/post.test.js
Add a response transformer to treat 404 responses from the claimant service as successful
> Handle not found response from claimant service outside of error handler

- src/test/acceptance/features/overview.feature
- src/web/routes/register-routes.js
- src/web/routes/start.js
This is a fix for bug: start page redirecting to itself after COMPLETE apply journey
> HTBHF-854 clear session data on start page if required

- package-lock.json
- package.json
- Updated `i18next-node-fs-backend` to fix `js-yaml` vulnerability
- Updated Nunjucks to ensure using latest version of node-gyp
- `node-gyp` imports vulnerable version of `tar`; listed `tar` as project dependency to deal with this. Following issue https://github.com/nodejs/node-gyp/issues/1714 so hopefully can remove this dependency in the future
> Update vulnerable npm packages

- src/test/common/page/confirm.js
- src/test/common/page/page.js
- src/test/common/steps/confirm-details.js
The content of the confirm page is liable to change as we iterate the apply journey. When this content changes the function `assertVoucherEntitlementValuesForAttr()` will allow quick updates to the acceptance tests by wrapping voucher entitlement values in `data` attributes e.g:
```
<span data-entitlement="total-voucher-value-four-weeks">{{ totalVoucherValueForFourWeeks }}</span>
```
The above HTML was introduced in a previous commit in `src/web/views/locales/en/confirm.html`. This PR asserts that the total voucher value for four weeks is correct.
> HTBHF-978 assert on total voucher value for four weeks

- src/web/routes/application/check/create-request-body.js
- src/web/routes/application/check/create-request-body.test.js
- Add `address` field to request body sent to claimant service
- `cardDeliveryAddress` has been left intact for backwards compatibility. Once the claimant service has been updated to accept `address` then `cardDeliveryAddress` can be removed
> HTBHF-1358 add address field to request body

- package-lock.json
`fs-stream` and `tar` are dependencies introduced by `node-sass`. As we do not explicitly import them into the project all updates exist in `package-lock.json` (there are no updates to `package.json`).
There is also an updated version of `puppeteer` which we use for e2e testing and introduced through `chromedriver`.
> HTBHF-1041 fix vulnerable fs-stream and tar introduced by node-sass

- src/web/routes/application/are-you-pregnant/are-you-pregnant.js
- src/web/routes/application/card-address/card-address.js
- src/web/routes/application/common/state-machine/get-next-for-step.js
- src/web/routes/application/common/state-machine/get-next-for-step.test.js
- src/web/routes/application/common/state-machine/state-machine.js
- src/web/routes/application/common/state-machine/state-machine.test.js
- src/web/routes/application/do-you-live-in-scotland/do-you-live-in-scotland.js
- src/web/routes/application/enter-dob/enter-dob.js
- src/web/routes/application/enter-name/enter-name.js
- src/web/routes/application/enter-nino/enter-nino.js
- src/web/routes/application/middleware/handle-path-request.test.js
- src/web/routes/application/middleware/handle-post-redirects.test.js
- src/web/routes/application/middleware/handle-post.test.js
- src/web/routes/application/phone-number/phone-number.js
- Create a function that accepts the request object and returns a string in order to determine a path for the next step. This allows for conditional rendering of the next step in the sequence.
- Update the state machine to implement this function when determining the next step for the `IN_PROGRESS` state.
- Update the steps configuration objects to use a function for the `next` property.
> Allow conditional next paths for step

- src/web/server/server.js
Fixes bug where the render function that handles errors from the session middleware did not have access to `req.t` (the function responsible for translating content).
> NO-JIRA make internationalisation available to session middleware

- src/web/routes/application/are-you-pregnant/validate.js
- src/web/routes/application/card-address/validate.js
- src/web/routes/application/common/test/apply-express-validation.js
- src/web/routes/application/common/validators.js
- src/web/routes/application/email-address/validate.js
- src/web/routes/application/enter-dob/validate.js
- src/web/routes/application/enter-name/validate.js
- src/web/routes/application/enter-nino/validate.js
- src/web/routes/application/middleware/handle-post.js
- src/web/routes/application/middleware/handle-post.test.js
- src/web/routes/application/phone-number/validate.js
- src/web/routes/application/terms-and-conditions/post.js
- src/web/routes/application/terms-and-conditions/post.test.js
- src/web/routes/application/terms-and-conditions/terms-and-conditions.js
This stops the following deprecation warning which has appeared after the recent upgrade to express validator:
`express-validator: requires to express-validator/check are deprecated.You should just use require("express-validator") instead`
> NO-JIRA Fix express-validator deprecation warning after recent upgrade.

- src/test/common/steps/are-you-pregnant.js
- src/web/routes/application/children-dob/validate.js
- src/web/routes/application/children-dob/validate.test.js
- src/web/routes/application/common/formatters/dates.js
- src/web/routes/application/common/formatters/dates.test.js
- src/web/routes/application/common/validators.js
- src/web/routes/application/common/validators.test.js
- src/web/server/locales/cy/validation.json
- src/web/server/locales/en/validation.json
- src/web/views/macros/htbhf-child-dob-input.njk
- Fix error message in child dob macro
- Add validation translations for child date of birth
- Add validator for date more than four months in the past
- Add extra validation for childrens‘ date of birth:
1. date more than four years in the past
2. name too long
> Childrens‘ date of birth validation

- src/test/acceptance/features/children-dob.feature
- src/test/common/dates.js
- src/test/common/page/add-children-dob.js
- src/test/common/steps/add-children-dob-steps.js
- src/test/common/steps/common-steps.js
- src/test/common/steps/navigation.js
- I've also made some changes around the wording of steps and the methods they use to prefer the word 'submit' over 'enter' when those steps enter the details and also click the continue button as a part of the one step.
- I'm also aware that adding the test for 10 children isn't a failure scenario and could possibly have been in a subsequent PR, I'm happy to remove it if people feel strongly enough.
- I've also added the ability to add a day increment to the date creation method so that the children can each have different dates of birth based on the current index value.
- The majority of the methods now allow providing a child name, but also have a default if the test doesn't care (which is also index based).
> HTBHF-1678 Add validation failure scenarios for Add Child DOB page, plus test for 10 children.

- package.json
- src/test/common/page/submittable-page.js
- src/web/views/check.njk
- src/web/views/templates/form.njk
We need this so we can differentiate the submit button from the remove child buttons, without this all the ATs fail on that page as they click the Remove child button.
> HTBHF-1704 Add id to submit button so it can be unique identified when there are multiple buttons on the page.

- src/web/routes/application/children-dob/decrement-keys.js
- src/web/routes/application/children-dob/decrement-keys.test.js
- src/web/routes/application/children-dob/predicates.js
- src/web/routes/application/children-dob/predicates.test.js
- src/web/routes/application/children-dob/remove-child-by-index.js
- src/web/routes/application/children-dob/remove-child-by-index.test.js
- src/web/routes/application/children-dob/selectors.js
Add functions for removing all child entries from the session once the remove button has been clicked. Process is: 
- Get all the entries from the session that start with 'childDob-'
- Remove all entries which are for the given index ('childDob-x')
- Rebuild the object with the remaining children entries re-indexed plus everything else (non-'childDob-x' entries)
- This will be handed back to be added back into the session.
NOTE - this PR does not plumb it in yet and change what's in the session, this will be done in a subsequent PR.
> HTBHF-1680 Add functions for removing all child entries from the session

- src/test/common/page/enter-children-dob.js
- src/web/routes/application/children-dob/predicates.js
- src/web/routes/application/children-dob/validate.js
- src/web/routes/application/children-dob/validate.test.js
- src/web/views/macros/htbhf-child-dob-input.njk
Update child name prefix for child DOB input to include `Dob`. This is required for removing a child from the session.
> HTBHF-1680 use DOB prefix for child's name

- src/web/routes/application/children-dob/children-dob.js
- src/web/routes/application/children-dob/children-dob.test.js
- src/web/routes/application/children-dob/constants.js
- src/web/routes/application/children-dob/handle-add-action.js
- src/web/routes/application/children-dob/handle-add-action.test.js
- src/web/routes/application/children-dob/handle-remove-action.js
- src/web/routes/application/children-dob/handle-remove-action.test.js
- src/web/routes/application/children-dob/remove-child-by-index.js
- src/web/routes/application/children-dob/set-children-in-session.js
- src/web/routes/application/children-dob/set-children-in-session.test.js
- src/web/views/children-dob.njk
- src/web/views/macros/htbhf-child-dob-input.njk
- Handle remove action when remove action is present on POST
- Refactor `behaviourForPost` into three distinct middleware functions (`setChildrenInSessionForPost`, `handleAddAction`, `handleRemoveAction`)
- Update unit tests to reflect this refactor
The main functional changes exist in `handleRemoveAction.js`. The remaining updates are mainly refactoring code to separate files.
> HTBHF-1680 enable remove action for children's DOB

- src/web/routes/application/are-you-pregnant/test/validate.test.js
- src/web/routes/application/are-you-pregnant/validate.js
- src/web/routes/application/children-dob/validate.js
- src/web/routes/application/children-dob/validate.test.js
- src/web/routes/application/common/validators.js
- src/web/routes/application/common/validators.test.js
- Fix error where a child with a DOB exactly four years ago would pass validation for “three years old or younger”
- Update validator for “one month in the past” to follow the same format
> HTBHF-1839 Fix date validation boundary errors

- src/test/common/page/are-you-pregnant.js
- src/test/common/page/card-address.js
- src/test/common/page/email-address.js
- src/test/common/page/enter-children-dob.js
- src/test/common/page/enter-code.js
- src/test/common/page/enter-dob.js
- src/test/common/page/enter-name.js
- src/test/common/page/enter-nino.js
- src/test/common/page/input-field.js
- src/test/common/page/page.js
- src/test/common/page/phone-number.js
- src/test/common/steps/are-you-pregnant.js
- src/test/common/steps/card-address-steps.js
- src/test/common/steps/common-steps.js
- src/test/common/steps/confirmation-code-navigation-steps.js
- src/test/common/steps/email-address-steps.js
- src/test/common/steps/enter-code-steps.js
- src/test/common/steps/enter-name-steps.js
- src/test/common/steps/enter-nino-steps.js
- src/test/common/steps/phone-number-steps.js
- All Page objects for a page which contains an input field have been refactored to use the InputField component.
- All InputFields objects are created on construction of the page object for reuse, the only exception where this is the Enter Child DOB page where the dynamic nature of the input fields means they need to be created each time before use.
- A TODO has been added to the Enter Child DOB Page object for when we fix the naming inconsistency within `htbhf-date-input.njk`, we'll also have to fix the name of the error CSS to match there.
> HTBHF-1836 Refactor page objects to use InputField component

- src/web/routes/application/check/get-row-data.js
- src/web/routes/application/check/get-row-data.test.js
- src/web/routes/application/check/get.js
- src/web/routes/application/check/get.test.js
Displaying check details for “About your children” will extend the functions for generating row data on the “check details” page. This PR moves these data transformation functions into a separate file in preparation for extending / refactoring.
> HTBHF-1853 move row data transformations to separate file

- src/test/acceptance/features/internationalisation.feature
- src/test/common/steps/overview-steps.js
- src/web/server/internationalisation.js
All language based tests have been disabled and TODOs added next to each so we can find them all again when translations are reinstated.
> HTBHF-1755 Disable language detection so that English is the only supported language.

- src/web/routes/application/check/constants.js
- src/web/routes/application/check/get-row-data.js
- src/web/routes/application/check/get-row-data.test.js
- src/web/routes/application/check/get.js
- src/web/views/check.njk
- src/web/views/macros/htbhf-summary-list.njk
Update the structure of the data consumed by the “check details” page to allow rendering multiple summary lists:
- Group the data passed to the view by list
- Refactor the summary list into a macro
- Refactor the page content structure to allow for easy translation of the summary list headings
> Group summary lists by list name

- src/test/common/page/check.js
- src/web/assets/sass/all.scss
- src/web/assets/sass/components/_children-summary-list.scss
- src/web/assets/sass/settings/_colors.scss
- src/web/routes/application/check/get.js
- src/web/server/locales/en/common.json
- src/web/views/check.njk
- src/web/views/macros/htbhf-children-summary-list.njk
- Wrap GOV.UK summary list macro to create a custom summary list for children’s dates of birth
- Display children’s dates of birth on “check details page”
- Update HTML structure and acceptance tests for “check details” page to allow the children’s dates of birth summary list to be tested independently (as it’s HTML structure will differ from the main summary list)
Adding acceptance tests for this update is quite involved so leaving for a separate (subsequent) PR.
> Display children’s dates of birth on “check details page”

- src/test/common/page/check.js
- src/test/common/page/page.js
- src/test/common/steps/check-details.js
- src/test/common/steps/constants.js
- Allow testing of children’s dates of birth summary list independently from claim summary list
- Assert single change link is shown for children’s dates of birth
- Remove legacy reference to `tableContents` (update to `contents`)
To do in next PR:
- Correctly format date
- Assert children’s dates of birth not shown
> Add acceptance tests for children’s dates of birth on “check details” page

- src/test/common/steps/constants.js
- src/web/routes/application/check/constants.js
- src/web/routes/application/check/get-childrens-dates-of-birth-rows.js
- src/web/routes/application/check/get-childrens-dates-of-birth-rows.test.js
- src/web/routes/application/check/get.js
- src/web/server/locales/cy/common.json
- src/web/server/locales/en/common.json
- src/web/views/check.njk
- src/web/views/macros/htbhf-children-summary-list.njk
- Move building of rows for children’s dates of birth summary list out of the view (this means we can reuse date formatters without creating a new Nunjucks filter. It also follows how the rows for the other summary lists are generated)
- Format children’s dates of birth in summary list
- Import correct date formatter in acceptance tests
> Format date for children’s dates of birth summary

- src/test/common/page/page.js
Create two base methods `findBy` and `findAllBy` that can be wrapped to create more specific webdriver selector methods.
> HTBHF-1852 refactor base page object selector methods

- src/test/acceptance/features/change-children.feature
- src/test/common/steps/check-details.js
- src/web/routes/application/children-dob/set-children-in-session.js
- src/web/routes/application/do-you-have-children-three-or-younger/do-you-have-children-three-or-younger.js
- src/web/routes/application/do-you-have-children-three-or-younger/do-you-have-children-three-or-younger.test.js
- src/web/routes/application/terms-and-conditions/create-request-body.js
- src/web/routes/application/terms-and-conditions/create-request-body.test.js
Remove children from session when changing answer for “Do you have children?” from “Yes” to “No”.
Checking children's existence on session is now implemented using `isNil` which allows for checking both `null` and `undefined`. An alternative would be to remove `children` using the `delete` operator.
> Remove children from session

- src/web/routes/guidance.js
- src/web/routes/guidance.test.js
- src/web/routes/register-routes.js
- src/web/views/guidance/how-it-works.njk
- src/web/views/templates/guidance.njk
- Created base Nunjucks template for guidance pages to extend from
- Registered route for first guidance page. This route will eventually change but is indicative of how all the guidance page routes will be registered
- Pass navigation meta data to the view
Future PRs to story branch will:
- Register other guidance page routes
- Deal with translations
- Display page content
- Display contents navigation
> Create basic guidance pages structure

- src/web/routes/guidance/get-page-meta-data.js
- src/web/routes/guidance/get-page-meta-data.test.js
- src/web/routes/guidance/guidance.js
In anticipation of adding new code to `guidance.js` this PR moves functions relating to `getPageMetadata()` into a separate file. No new code added.
> HTBHF-1971 restructure guidance directory

- src/web/routes/guidance/get-page-meta-data.js
- src/web/routes/guidance/get-page-meta-data.test.js
- src/web/routes/guidance/guidance.js
- src/web/server/locales/cy/common.json
- src/web/server/locales/en/common.json
- src/web/views/macros/htbhf-pagination.njk
- src/web/views/templates/guidance.njk
- Rename previous and next parameters to differentiate between pages and labels
- Add translations for guidance pages
- Remove `title` from page meta as it’s not used in the template - this removes `getPageForPath` function and tests as no longer required
> Guidance page translations

- src/test/acceptance/features/guidance-pages.feature
- src/test/common/page/guidance.js
- src/test/common/page/page.js
- src/test/common/page/submittable-page-with-radio-buttons.js
- src/test/common/steps/guidance-steps.js
- src/test/common/steps/pages.js
- src/web/routes/guidance/get-page-meta-data.js
- src/web/routes/guidance/get-page-meta-data.test.js
- src/web/routes/guidance/guidance.js
- src/web/routes/guidance/index.js
- src/web/routes/guidance/pages.js
- src/web/server/locales/en/common.json
- src/web/views/templates/guidance.njk
- The page object for guidance pages is a bit different because it encapsulates all the guidance pages so has its own navigation step and function.
- The tests themselves assert that the headers are correct, that there a links for all pages (table of contents) apart from the page itself, plus there are previous and next links if applicable. There are no assertions for actual content.
This was my best stab at getting the feature file correct, please feel free to suggest alternatives, I found it quite hard to get them right so they might not be perfect yet.
> HTBHF-1964 Add acceptance tests for guidance pages.

- src/web/routes/guidance/guidance.js
- src/web/routes/guidance/pages.js
- src/web/views/guidance/en/what-you-get.njk
Preparation for replacing current page on base URL with the guidance pages:
- Add missing classes to links
- Add template to pages object
> Add template prop to guidance pages

- .travis.yml
Chrome has been crashing much more than previously - this is in case the new linux version was to blame.
> HTBHF-1972 changed travis linux version to trusty (downgrade from bionic)

- src/web/routes/register-steps/register-steps.js
- src/web/routes/register-steps/register-steps.test.js
- src/web/routes/register-steps/to-boolean-strict.js
- src/web/routes/register-steps/to-boolean-strict.test.js
- coerce string representations for true and false to boolean (as assumed to be from environment variables)
- remove type checks in `registerSteps` handled by boolean coercion
- add description to functions
> HTBHF-2045 refactor register steps

- src/web/routes/application/are-you-pregnant/are-you-pregnant.js
- src/web/routes/application/children-dob/children-dob.js
- src/web/routes/application/common/state-machine/get-next-for-step.js
- src/web/routes/application/common/state-machine/get-next-for-step.test.js
- src/web/routes/application/common/state-machine/state-machine.js
- src/web/routes/application/email-address/email-address.js
- src/web/routes/application/enter-code/enter-code.js
- src/web/routes/application/enter-dob/enter-dob.js
- src/web/routes/application/enter-name/enter-name.js
- src/web/routes/application/enter-nino/enter-nino.js
- src/web/routes/application/manual-address/manual-address.js
- src/web/routes/application/middleware/handle-post.test.js
- src/web/routes/application/phone-number/phone-number.js
- src/web/routes/application/send-code/send-code.js
- Update `getNextForStep` to dynamically determine the next path in the sequence
- Remove redundant error tests for `handlePost`
- Remove `next` prop on steps that reference the next step in sequence of steps
This does not affect steps that determine the next path based on the session - if a function is used for `next` prop on step it will take precedence over the default dynamic behaviour.
> HTBHF-2045 dynamically determine next path

- src/config/features.js
- src/config/index.js
- src/web/routes/register-routes.js
- src/web/routes/register-steps/index.js
- src/web/routes/register-steps/predicates.js
- src/web/routes/register-steps/predicates.test.js
- src/web/routes/register-steps/register-steps.js
- src/web/routes/register-steps/register-steps.test.js
- src/web/routes/register-steps/to-boolean-strict.js
- src/web/routes/register-steps/to-boolean-strict.test.js
Allow steps to be toggled off on application start based on config:
- Register steps on application start based on settings in `config.features`
- Pass registered steps to middleware instead of all steps
> Feature toggle

- src/test/common/steps/check-details.js
- src/test/common/steps/common-steps.js
- src/test/common/steps/confirmation-code-navigation-steps.js
- src/test/common/steps/manual-address-steps.js
- src/test/common/steps/navigation/step-page-actions.js
The new address pages will make the current function name confusing, as such it should be renamed from address to manualAddress.
> HTBHF-2047 Renamed enterAddressAndSubmit to enterManualAddressAndSubmit

- src/test/common/steps/check-answers.js
- src/test/common/steps/confirmation-code-navigation-steps.js
- src/test/common/steps/navigation/navigation.js
- src/test/common/steps/navigation/steps.js
A few functions were using `page` as a parameter name where they were actually expecting a page name. These parameters have been renamed to `pageName` to prevent confusion in the future.
> HTBHF-2037 Renamed incorrect page parameter to pageName.

- src/test/common/steps/address-lookup-steps.js
- src/test/common/wiremock/postcode-lookup/index.js
Previously the acceptance tests asserted that every `option` in the `select` for address lookup contained the correct postcode. This no longer works as the postcode has been removed from each option.
It’s important to assert that each `option` contains text (instead of just asserting that the correct number of `option` elements exist). So we need to:
- Get the results returned by the API response (from the Wiremock mapping)
- Iterate over each `option` web element returned by Selenium
- Check that the text matches the corresponding result in the API response
> HTBHF-2037 fix select address options acceptance test

- src/web/routes/application/address/manual-address/manual-address.js
- src/web/routes/application/address/manual-address/maunal-address.test.js
- src/web/routes/application/address/request-body.js
- src/web/routes/application/address/request-body.test.js
- src/web/routes/application/address/select-address/select-address.js
- src/web/routes/application/are-you-pregnant/are-you-pregnant.js
- src/web/routes/application/are-you-pregnant/request-body.js
- src/web/routes/application/are-you-pregnant/request-body.test.js
- src/web/routes/application/child-date-of-birth/child-date-of-birth.js
- src/web/routes/application/child-date-of-birth/request-body.js
- src/web/routes/application/child-date-of-birth/request-body.test.js
- src/web/routes/application/date-of-birth/date-of-birth.js
- src/web/routes/application/date-of-birth/date-of-birth.test.js
- src/web/routes/application/email-address/email-address.js
- src/web/routes/application/email-address/email-address.test.js
- src/web/routes/application/name/name.js
- src/web/routes/application/name/name.test.js
- src/web/routes/application/national-insurance-number/national-insurance-number.js
- src/web/routes/application/national-insurance-number/national-insurance-number.test.js
- src/web/routes/application/phone-number/phone-number.js
- src/web/routes/application/phone-number/phone-number.test.js
- src/web/routes/application/terms-and-conditions/create-request-body.js
- src/web/routes/application/terms-and-conditions/create-request-body.test.js
- src/web/routes/application/terms-and-conditions/post.js
The general rule of the application is to define logic and  data transformations at the step level. It therefore makes sense that the properties for the request body should also be defined at the step level. The benefits of this approach are:
1. Related code is all in one place in the application architecture
2. Toggling a step will mean the relevant part of the request body is also toggled
3. Easier to unit test individual parts of the request body
The acceptance test that checks the request body being sent to the server should give us confidence to make this update. A lot of the PR is moving code from `create-request-body.js` to the relevant steps:
- Create a function that iterates over each step to generate the request body that is sent to the server
- Move definition of request body …
> Define properties for request body at step level

- src/web/routes/application/address/formats.js
- src/web/routes/application/address/formats.test.js
- src/web/routes/application/address/postcode/adapters.js
- src/web/routes/application/address/postcode/adapters.test.js
- src/web/routes/application/address/postcode/postcode.test.js
- src/web/routes/application/address/select-address/adapters.addresses.test.js
- src/web/routes/application/address/select-address/adapters.js
- src/web/routes/application/address/select-address/select-address.test.js
Minimise the number of address transforms performed during postcode lookup by:
- Only transforming the single line address field of each result from OS Places API response to title case (instead of all address fields)
- Only converting the full address of the selected address to title case (instead of all addresses)
> HTBHF-2297 minimise redundant address transforms

- src/web/routes/application/common/test/apply-express-validation.js
- src/web/routes/application/email-address/validate.js
- src/web/routes/application/email-address/validate.test.js
The express validation library we implement wraps validator JS which implements an email validation check. It seems better to use an actively maintained validator rather than trying to maintain our own regex (unoptimised regex can have significant performance implications for node).
- Replace custom regex email validation with validator from validation library
- Remove explicit max length validation as email validation implicitly checks for length
- Add unit tests for validation middleware
- Add translation function to express validation test helper function
> No-JIRA use library email validation

- src/web/views/guidance/en/report-a-change.njk
Replace warning HTML for macro to allow for easier upgrading of GOV.UK frontend
> HTBHF-2359 implement warning macro on guidance page

- src/test/common/constants.js
- src/test/common/wiremock/claim/claim.js
- src/test/common/wiremock/claim/mappings.js
- src/test/common/wiremock/postcode-lookup/mappings.js
- src/test/common/wiremock/postcode-lookup/postcode-lookup.js
Remove redundant wiremock mappings from test directory. Leave mappings used for a11y / integration tests.
> NO-JIRA remove redundant wiremock mappings

- src/web/routes/guidance/guidance.js
- src/web/routes/guidance/guidance.test.js
- src/web/routes/register-routes.js
- test_versions.properties
Enabler for implementing multiple user journeys. Removes the handle path request middleware from guidance routes and therefore the requirement for `steps` when registering guidance routes.
> Decouple guidance pages from journey middleware

- src/web/routes/application/address/select-address/select-address.js
- src/web/routes/application/check-answers/get.js
- src/web/routes/application/common/state-machine/state-machine.js
- src/web/routes/application/common/state-machine/state-machine.test.js
- src/web/routes/application/middleware/handle-path-request/handle-path-request.js
- src/web/routes/application/middleware/handle-post.js
- src/web/routes/application/terms-and-conditions/post.js
EPIC: UI support multiple journeys
Route all middleware operations that set the next allowed path in session through the state machine (instead of mutating the session directly). Future PRs will update the state machine to query the user journey when setting this state.
- Create state machine `SET_NEXT_ALLOWED_PATH` action 
- Update middleware session mutations to call state machine
> Call state machine to set next allowed path

- src/web/routes/application/index.js
- src/web/routes/application/register-form-routes.js
- src/web/routes/register-routes.js
Move registering of `/check-answers`, `/terms-and-conditions` and `/confirm` routes so they are registered alongside the other apply journey routes. This will enable registering of these route handlers for any new journeys.
> HTBHF-2503 register all application routes with steps

- src/web/routes/application/check-answers/check-answers.js
- src/web/routes/application/check-answers/get.js
- src/web/routes/application/confirm/confirm.js
- src/web/routes/application/middleware/handle-path-request/handle-path-request.js
- src/web/routes/application/middleware/handle-path-request/handle-path-request.test.js
- src/web/routes/application/middleware/handle-post-redirects.js
- src/web/routes/application/middleware/handle-post-redirects.test.js
- src/web/routes/application/middleware/handle-post.js
- src/web/routes/application/middleware/handle-post.test.js
- src/web/routes/application/register-journey-routes.js
- src/web/routes/application/terms-and-conditions/get.js
- src/web/routes/application/terms-and-conditions/post.js
- src/web/routes/application/terms-and-conditions/post.test.js
- src/web/routes/application/terms-and-conditions/terms-and-conditions.js
To enable multiple user journeys the state machine needs to be journey aware. This PR passes the `journey` object to all middleware and route handlers that call the state machine.
Future PRs will call the state machine with the `journey` object to enable journey specific state updates.
> HTBHF-2523 consume journey in route handlers

- src/web/routes/application/flow-control/state-machine/actions.js
- src/web/routes/application/flow-control/state-machine/index.js
- src/web/routes/application/flow-control/state-machine/operators.js
- src/web/routes/application/flow-control/state-machine/predicates.js
- src/web/routes/application/flow-control/state-machine/predicates.test.js
- src/web/routes/application/flow-control/state-machine/selectors/get-next-for-step.js
- src/web/routes/application/flow-control/state-machine/selectors/get-next-for-step.test.js
- src/web/routes/application/flow-control/state-machine/selectors/index.js
- src/web/routes/application/flow-control/state-machine/selectors/selectors.js
- src/web/routes/application/flow-control/state-machine/state-machine.js
- src/web/routes/application/flow-control/state-machine/state-machine.test.js
- src/web/routes/application/flow-control/state-machine/states.js
HTBHF-2515 requires a number of updates to the state machine to enable journey specific updates to the session.
This PR is a precursory refactor to reduce the noise in the state machine and focus on the state specific actions. No new logic has been added:
- Move states and actions to separate files (actions were not used directly in state machine)
- Create predicates and selectors files
- Create an operators file - this will be expanded in future PRs for HTBHF-2544 as it will control how journey state is set in session
> HTBHF-2544 refactor state machine

- src/web/routes/application/flow-control/middleware/handle-path-request/handle-path-request.js
- src/web/routes/application/flow-control/middleware/handle-post-redirects.js
- src/web/routes/application/flow-control/middleware/handle-post.js
- src/web/routes/application/flow-control/state-machine/operators.js
- src/web/routes/application/flow-control/state-machine/state-machine.js
- src/web/routes/application/flow-control/state-machine/state-machine.test.js
- src/web/routes/application/steps/address/select-address/select-address.js
- src/web/routes/application/steps/check-answers/get.js
- src/web/routes/application/steps/terms-and-conditions/post.js
To implement multiple user journeys the state machine will need to know about the active journey:
- Make `journey` a mandatory argument for `stateMachine.dispatch()`
- Update calls to the state machine to use the `journey` argument, replacing arguments that were previously a property of `journey` (e.g. `journey.steps` and `journey.pathsInSequence`)
> HTBHF-2546 pass journey as argument when calling state machine dispatch

- src/web/routes/application/flow-control/middleware/session-details.js
- src/web/routes/application/flow-control/middleware/session-details.test.js
- src/web/routes/application/journey-definitions.js
- src/web/routes/application/register-journey-routes.js
- test_versions.properties
Initialise journey in session on route request. This is a non breaking change as the application has not been updated to determine flow control from journey state:
- Initialise a default journey state when a journey path is requested
- Rename session details middleware and give it a reference to the journey
- Add missing unit test for session details (adding claim to `res.locals`)
- Name the apply journey to enable the journey session initialisation
> HTBHF-2547 initialise journey in session

- src/web/routes/application/flow-control/middleware/handle-path-request/handle-path-request.js
- src/web/routes/application/flow-control/middleware/handle-path-request/handle-path-request.test.js
- src/web/routes/application/flow-control/middleware/handle-post-redirects.test.js
- src/web/routes/application/flow-control/middleware/handle-post.js
- src/web/routes/application/flow-control/middleware/handle-post.test.js
- src/web/routes/application/flow-control/state-machine/session-accessors.js
- src/web/routes/application/flow-control/state-machine/state-machine.js
- src/web/routes/application/flow-control/state-machine/state-machine.test.js
- src/web/routes/application/flow-control/state-machine/test-utils/test-utils.js
- src/web/routes/application/flow-control/state-machine/test-utils/test-utils.test.js
- src/web/routes/application/steps/address/postcode/postcode.js
- src/web/routes/application/steps/address/postcode/postcode.test.js
- src/web/routes/application/steps/address/select-address/select-address.test.js
- src/web/routes/application/steps/check-answers/get.js
- src/web/routes/application/steps/common/confirmation-code.js
- src/web/routes/application/steps/common/confirmation-code.test.js
- src/web/routes/application/steps/email-address/email-address.js
- src/web/routes/application/steps/phone-number/phone-number.js
- src/web/routes/application/steps/terms-and-conditions/get.js
- src/web/routes/application/steps/terms-and-conditions/post.js
- src/web/routes/application/steps/terms-and-conditions/post.test.js
This is a breaking change as the shape of the session is being updated. Any active users with active sessions when this update reaches production will encounter errors the next time they make a request from the server:
- Update the state machine to read and write to the correct part of the session depending on the journey associated with the requested route
- Update all code that calls the state machine to pass the journey as an argument
- Update unit tests to reflect the change in session shape
> HTBHF-2548 get and set journey session state

- src/web/routes/application/flow-control/middleware/handle-path-request/handle-path-request.js
- src/web/routes/application/flow-control/state-machine/selectors/get-next-for-step.js
- src/web/routes/application/flow-control/state-machine/selectors/get-next-for-step.test.js
- src/web/routes/application/flow-control/state-machine/selectors/selectors.js
- src/web/routes/application/flow-control/state-machine/state-machine.js
- src/web/routes/application/steps/check-answers/check-answers.js
- src/web/routes/application/steps/check-answers/get.js
- src/web/routes/application/steps/confirm/confirm.js
- src/web/routes/application/steps/terms-and-conditions/get.js
- src/web/routes/application/steps/terms-and-conditions/post.js
- src/web/routes/application/steps/terms-and-conditions/terms-and-conditions.js
- src/web/views/check-answers.njk
Update any uses of constant journey URLs (`CHECK_ANSWERS_URL` / `TERMS_AND_CONDITIONS_URL` / `CONFIRM_URL`) to implement `pathPrefix()`. This ensures these URLs are prefixed with `journey.pathPrefix` where required.
As there is no `pathPrefix` property defined on the apply journey this does not impact the routing of the current apply journey:
- Update signature of state machine selector functions to use `journey` instead of `steps` where `journey.pathPrefix` is required
- Implement `pathPrefix` when referencing constant URLs in route handlers / state machine
- Implement `pathPrefix` when registering routes using constant URLs
- Update template references to constant URLs to implement `pathPrefix`
> HTBHF-2595 prefix constant journey paths

- src/web/routes/application/register-journeys.js
- src/web/routes/application/register-journeys.test.js
Apply path prefix to journey steps when registering a journey:
- Apply path prefix to the `path` property of each journey step
- Apply path prefix to each path in `journey.pathsInSequence` array
> HTBHF-2595 apply path prefix when registering journeys

- src/web/routes/application/steps/are-you-pregnant/are-you-pregnant.js
- src/web/server/locales/cy/common.json
- src/web/server/locales/en/common.json
- src/web/views/are-you-pregnant.njk
- Added a form description to the are you pregnant page.
- The fieldSet options within govukRadios does not support having hint text (hint text is only available for the labels), so the radio buttons were extracted to be wrapped within a govukFieldset block and a htbhfFormDescription is used for the hint. (This is the same pattern we use for manual-address).
> HTBHF-2482 Added form description to are you pregnant page.

- src/web/views/macros/htbhf-form-description.njk
The update of govuk frontend to version 3 added a bottom margin to the class `govuk-body`, we therefore now no longer need to add `govuk-!-padding-bottom-4` to htbhfFormDescription. Doing so adds too much spacing (noticeably more than the prototype).
> HTBHF-2482 Remove unnecessary padding from form description macro.

- src/web/routes/application/flow-control/middleware/handle-path-request/handle-path-request.js
- src/web/routes/application/flow-control/middleware/handle-path-request/handle-path-request.test.js
- src/web/routes/application/flow-control/middleware/handle-path-request/predicates.js
- src/web/routes/application/flow-control/middleware/handle-path-request/predicates.test.js
- src/web/routes/application/flow-control/session-accessors/index.js
- src/web/routes/application/flow-control/session-accessors/session-accessors.js
- src/web/routes/application/flow-control/session-accessors/session-accessors.test.js
Fixes a bug where changing between journey routes after completing a journey would not destroy the session.
- Update journey middleware to check the session for **_ANY_** completed journeys
- If a completed journey exists: destroy the session and redirect to the first path of the active journey
> HTBHF-2507 destroy session if any COMPLETED journeys exist in session

- sample.env
- src/test/a11y/paths.js
- Simplify base URL environment variables
- Remove Browserstack environment variables (not used in UI)
- Create structure for environment variables in `sample.env`
> NO-JIRA tidy environment variables

- src/web/routes/application/steps/terms-and-conditions/post.js
- src/web/routes/application/steps/terms-and-conditions/post.test.js
- test_versions.properties
Fix bug where redirect to `/decision` page did not include journey path prefix URL segment. This resulted in always redirecting to the `nextAllowedPath` in the apply journey.
Also incremented acceptance tests version to latest release.
> HTBHF-2490 fix decision redirect

- src/web/routes/application/flow-control/middleware/handle-post.js
- src/web/routes/application/flow-control/middleware/handle-post.test.js
In the case of a validation error on form data, we have been populating the response body only with the content from the request (so, e.g. if there was a problem with the NINO the response would include the NINO from the request, not the NINO stored in the session - if any). This change adds values form the claim in the session as well - in case the form displays information from the claim as well as data entry fields.
> HTBHF-2675 Add the claim as well as request body to res.locals in error cases

- src/web/routes/application/steps/decision/decision.js
- src/web/routes/application/steps/decision/decision.test.js
Tidying up the `/decision` route handler in preparation for "receive my decision" epic.
Removed error check that is the domain of the claimant service. UI should not need to validate data it receives from an API.
> HTBHF-2014 remove extraneous error check

- src/web/routes/application/steps/decision/decision.js
- src/web/routes/application/steps/decision/decision.test.js
- src/web/routes/application/steps/terms-and-conditions/post.js
- src/web/routes/application/steps/terms-and-conditions/post.test.js
- src/web/server/locales/cy/common.json
- src/web/server/locales/en/common.json
- test_versions.properties
The default "apply" journey no longer has a requirement to handle updated claims. The UI now ignores the `claimUpdated` flag in the claimant service response.
> HTBHF-2683 ignore claim updated flag in claimant service response

- src/test/a11y/constants.js
Updated `generateEligibleNino` function in test code to match new NINO requirements in claimant service V3 endpoint.
No unit test included as there is not a reliable way of testing against invalid NINOs. If this function does not work then CD pipeline would break.
> HTBHF-1942 update test NINO to match V3 claimant service

- src/web/routes/application/steps/decision/get-decision-status.js
- src/web/routes/application/steps/decision/get-decision-status.test.js
`getDecisionStatus` consumes `verificationResult` returned from the claimant service. Ultimately this function will return one of four values:
- SUCCESS
- FAIL
- PENDING
- undefined
In a future PR `getDecisionStatus` will be implemented in the `/decision` route handler to determine which decision template to render.
> HTBHF-1942 determine decision status for failure scenarios

- src/web/routes/application/steps/decision/get-decision-status.js
- src/web/routes/application/steps/decision/get-decision-status.test.js
- src/web/routes/application/steps/decision/statuses.js
- src/web/routes/application/steps/terms-and-conditions/post.js
- src/web/routes/application/steps/terms-and-conditions/post.test.js
- test_versions.properties
Make `verificationResult` available between route handlers. Preparation for "receive decision" view handling:
- Set `verificationResult` on session to make it accessible between routes
- Extract decision `statuses` for easier reuse between files
> HTBHF-1942 persist verification result

- src/web/routes/application/steps/decision/decision-fallback.js
- src/web/routes/application/steps/decision/decision.js
- src/web/routes/application/steps/decision/decision.test.js
- src/web/server/locales/cy/common.json
- src/web/server/locales/en/common.json
- src/web/views/decision/failure.njk
- src/web/views/locales/en/decision/failure.njk
- test_versions.properties
Handle failure scenarios for "receive my decision":
- Identity not matched
- Eligibility not confirmed
Based on these scenarios the `/decision` route handler will render a failure screen, otherwise it will fallback to the default claimant service response handling:
- Add missing `decision fallback` renames in translations
- Add `.njk` decision failure template
- Handle verification failure scenarios
- Fallback to default `/decision` route handler if scenarios are not matched
> HTBHF-1942 render instant failure decision

- src/web/routes/application/steps/decision/decision.js
- src/web/routes/application/steps/decision/eligibility-statuses.js
- src/web/routes/application/steps/decision/get-decision-status.js
- src/web/routes/application/steps/decision/get-decision-status.test.js
- test_versions.properties
Handle duplicate decision response from claimant service and render failure screen. This involves a refactor of `getDecisionStatus` to accept `eligibilityStatus` as an argument.
> HTBHF-2725 handle duplicate claim decision

- src/web/routes/application/steps/decision/decision.js
- src/web/routes/application/steps/decision/decision.test.js
- src/web/routes/application/steps/decision/get-decision-status.js
- src/web/routes/application/steps/decision/get-decision-status.test.js
- src/web/server/locales/cy/common.json
- src/web/server/locales/en/common.json
- src/web/views/decision/pending.njk
- src/web/views/locales/en/decision/pending.njk
- test_versions.properties
Render "we're considering your application" content when applicant's address mismatches:
- Create PENDING `.njk` template
- Update decision engine to handle address mismatch
- Update `or` statements in decision engine to use ramda's `anyPass`. This is a preemptive refactor for adding more conditions to `isFailure` in the next update e.g:
```
const isFailure = anyPass([identityOutcomeNotMatched, eligibilityOutcomeNotConfirmed, isIneligibleClaim])
```
> HTBHF-1943 address mismatch decision view

- src/web/routes/application/steps/address/postcode/validate.js
- src/web/routes/application/steps/address/sanitize.js
- src/web/routes/application/steps/address/sanitize.test.js
The new variable sanitizedPostcode is only used by validate as the address lookup code already performs sanitization (converts to upper and strips all whitespace) before calling os places.
> AFHS-370 Sanitized postcodes are saved to a new variable.

- src/web/server/locales/cy/common.json
- src/web/server/locales/en/common.json
- test_versions.properties
The text `decision.pending.body` was being added to the pending decision page, setting the value to a blank String removes this. I'll add an acceptance test for this in a different PR in the acceptance-test module.
> HTBHF-2032 Fix issue with sub-title key being shown on pending decision page.

- src/web/routes/application/steps/decision/decision.js
- src/web/routes/application/steps/decision/decision.test.js
- src/web/routes/application/steps/decision/get-decision-status.js
- src/web/routes/application/steps/decision/get-decision-status.test.js
- src/web/server/locales/cy/common.json
- src/web/server/locales/en/common.json
- src/web/views/locales/en/decision/success.njk
It turns out that the success route was still using the fallback code to process and show the decision page, so have now added this specifically to decision.js and added in its template.
Once this is in we should now be able to remove the fallback code completely.
> AFHS-588 Add success decision logic to decision.js and add success decision template.

- src/test/a11y/tests/apply.js
- src/web/routes/application/steps/address/content-summary.test.js
- src/web/routes/application/steps/address/manual-address/maunal-address.test.js
- src/web/routes/application/steps/address/manual-address/test/validation-composition.test.js
- src/web/routes/application/steps/address/request-body.test.js
- src/web/routes/application/steps/address/sanitize.test.js
- src/web/routes/application/steps/address/select-address/select-address.test.js
- src/web/routes/application/steps/check-answers/get-row-data.test.js
Replaced all usages of Baker Street, London with Fake Street, Springfield. Also replaced the AA1 1AA postcode (which doesn't exist, and causes all postcode data to be NOT_FOUND in Google Analytics) with BS1 4TB.
> NO-JIRA replaced all test addresses with Fake Street, Springfield

- src/test/a11y/wiremock/claim/mappings/v3.js
- src/web/routes/application/steps/decision/get-decision-status.test.js
This is not used in code, only when mocking the response from the claimant service
> AFHS-1838 Replaced QualifyingBenefits with QualifyingReason. 
